import Head from "next/head";
import {ReactNode} from "react";
import styled from "styled-components";
import NavBar from "../NavBar/NavBar";

export const PageContainer = styled.div `
    max-width: 1200px;
    height: 100%;
    width: 100%;
    margin: 0 auto;
`
type PageContainerProp = {
    children: ReactNode
}


const Container = ({children} : PageContainerProp) => {
    return (
        <>
            <Head>
                <title>Events</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <NavBar/>
            <PageContainer>
                <main> {children} </main>
            </PageContainer>
        </>
    )
}

export default Container
